### ISSUE TITLE
Key in Object

### ISSUE THREAD

**Issue by psteinroe** [rossmartin/ionic2-alpha-scroll#1]
Hi,
first of all, thanks for this awesome alpha scroll!

I am using an array consisting of objects:
`"results": [
    {
      "gender": "male",
      "name": {
        "title": "mr",
        "first": "samuel",
        "last": "ross"
      },
      "location": {
        "street": "5592 pockrus page rd",
        "city": "santa ana",
        "state": "oregon",
        "postcode": 69974
      },`

Now I want to use the last name as key. While key = "gender" is working fine key = "name.last" is not working.
I get the error :"[Error] ORIGINAL EXCEPTION: TypeError: undefined is not an object (evaluating 'this.listData[i][this.key].toUpperCase')
    logError (app.bundle.js:44242)
    call (app.bundle.js:1907)
    (anonymous function) (app.bundle.js:25728)
    (anonymous function) (app.bundle.js:1370)
    __tryOrUnsub (app.bundle.js:111536)
    next (app.bundle.js:111485)
    _next (app.bundle.js:111435)
    next (app.bundle.js:111399)
    _finalNext (app.bundle.js:111191)
    _next (app.bundle.js:111183)
    next (app.bundle.js:111140)
    emit (app.bundle.js:1358)
    onHandleError (app.bundle.js:37403)
    handleError (zone.js:336)
    runTask (zone.js:268)
    drainMicroTaskQueue (zone.js:491)
    invoke (zone.js:435)"

Is it possible to fix this? I tried several solutions, but I do not want to reformat the JSON.

Thanks!

**Comment by rossmartin** [comment]
Hey you're welcome.  I'll be able to take a look in a few hours and we can get this figured out.

**Comment by rossmartin** [comment]
Just now getting to this, it was a busy day with work and after.

**Comment by rossmartin** [comment]
The issue is fixed in version 1.0.3 - you can uninstall your current version and reinstall then it will work.
