### ISSUE TITLE
Make component work with AoT compiling

### ISSUE THREAD

**Issue by rossmartin** [rossmartin/ionic2-alpha-scroll#11]
I cannot get AoT compiling to work currently. I am looking into how to make this possible with the Ionic 2.0.0 stable release. If anyone knows how to make it compatible with AoT please submit a pull request.

**Comment by julianlecalvez** [comment]
ok I think I fixed the problem by upgrading typescript to 2.1.5 

EDIT : actually it didn't fix the pb, but I still get an error on lodash (I didn't get it last week it's weird) :

```
[15:55:17]  typescript: node_modules/@types/lodash/index.d.ts, line: 245 
            Cannot find name 'Partial'. 
     L245:      compact<TResult>(): LoDashImplicitArrayWrapper<TResult>;
[15:55:17]  transpile failed 
[15:55:17]  ionic-app-script task: "build" 
[15:55:17]  Error: Error 
```

**Comment by rossmartin** [comment]
@julianlecalvez Yeah it appears that some of the latest versions of the `@types/lodash` definitions are broken.  I locked in the dependency versions for lodash in the latest version (1.1.1).  The error on lodash is gone now.  

Thanks for looking into it.

**Comment by julianlecalvez** [comment]
@rossmartin perfect ! it works !!
thanks a lot !

**Comment by julianlecalvez** [comment]
Argh, maybe I have a bad news :( 

it seems that the compilation passes but the execution not (on Android with the apk release). 
I get this error when I try to access the view that contains the alpha-scroll : 
```
main.js:23 EXCEPTION: No provider for t!
    t.handleError @ main.js:23
    e.onError.subscribe.next @ main.js:16
    e.object.r @ main.js:23
    e.__tryOrUnsub @ main.js:43
    e.next @ main.js:43
    e._next @ main.js:43
    e.next @ main.js:43
    e.next @ main.js:14
    e.emit @ main.js:23
    t.triggerError @ main.js:3
    inner.inner.fork.onHandleError @ main.js:3
    t.handleError @ polyfills.js:3
    e.runTask @ polyfills.js:3
    invoke @ polyfills.js:3

main.js:23 Error: No provider for t!
    at e.Error (native)
    at e [as constructor] (file:///android_asset/www/build/main.js:7:27316)
    at e [as constructor] (file:///android_asset/www/build/main.js:31:7138)
    at new e (file:///android_asset/www/build/main.js:31:7465)
    at t._throwOrNull (file:///android_asset/www/build/main.js:47:7966)
    at t._getByKeyDefault (file:///android_asset/www/build/main.js:47:8322)
    at t._getByKey (file:///android_asset/www/build/main.js:47:7876)
    at t.get (file:///android_asset/www/build/main.js:47:4238)
    at e.Object.defineProperty.get [as _Compiler_29] (file:///android_asset/www/build/main.js:43:16611)
    at e.getInternal (file:///android_asset/www/build/main.js:43:28884)t.handleError @ main.js:23e.onError.subscribe.next @ main.js:16e.object.r @ main.js:23e.__tryOrUnsub @ main.js:43e.next @ main.js:43e._next @ main.js:43e.next @ main.js:43e.next @ main.js:14e.emit @ main.js:23t.triggerError @ main.js:3inner.inner.fork.onHandleError @ main.js:3t.handleError @ polyfills.js:3e.runTask @ polyfills.js:3invoke @ polyfills.js:3

main.js:43 Uncaught Error: No provider for t!
```

:(

**Comment by rossmartin** [comment]
That will occur if you build with the `--prod` flag.  The issue with AoT compiling is related to what is described here - https://github.com/laco0416/ng-dynamic#dynamiccomponent-constraints

The problem is that there is no `main.prod.ts` anymore and if you try and use `platformBrowser` in the new `main.ts` it bombs out.  When there was a `main.prod.ts` you could do this below in it and AoT would work - 

```
import { platformBrowser } from '@angular/platform-browser';
import { enableProdMode } from '@angular/core';
import { COMPILER_PROVIDERS } from '@angular/compiler'; // import this

import { AppModuleNgFactory } from './app.module.ngfactory';

enableProdMode();
platformBrowser([
  COMPILER_PROVIDERS // dynamic content project used by ionic2-alpha-scroll needs this
]).bootstrapModuleFactory(AppModuleNgFactory);
```

**Comment by MoemenMostafa** [comment]
Any updates regarding this issue?

**Comment by rossmartin** [comment]
@MoemenMostafa Sorry I haven't had time to look into it.

**Comment by squallliu** [comment]
try replacing ng-dynamic with ngTemplateOutlet
`
<template [ngTemplateOutlet]="alphaScrollTemplate" [ngOutletContext]="ionAlphaScrollRef"></template>
`

**Comment by rossmartin** [comment]
@squallliu Thanks I wasn't aware of `ngTemplateOutlet` I'll try it out.

**Comment by rossmartin** [comment]
@squallliu Not looking to be an easy replacement unfortunately and `ngTemplateOutlet` is labeled as experimental.   I'll look into it some more soon.

**Comment by anishtr4** [comment]
Any updates on this ?

**Comment by rossmartin** [comment]
resolved via https://github.com/rossmartin/ionic2-alpha-scroll/pull/17

New major version 2.0.0 is available with this PR.
