### ISSUE TITLE
App break after installation

### ISSUE THREAD

**Issue by FrancescoMussi** [rossmartin/ionic2-alpha-scroll#12]
I was testing the component on a fresh app.

The app breaks after the installation.

There is something wrong with lodash file.
After removing the component the app works fine again.

This is the error message:

![screen shot 2017-01-31 at 11 21 24](https://cloud.githubusercontent.com/assets/5312907/22460996/caf395ca-e7a7-11e6-9d71-843520e70fb8.png)

**Comment by rossmartin** [comment]
Thanks for reporting I should be able to look into it tonight.

**Comment by rossmartin** [comment]
Fixed in version 1.1.1 - Thanks.
