### ISSUE TITLE
Support Ionic 4

### ISSUE THREAD

**Issue by aBuder** [rossmartin/ionic2-alpha-scroll#16]
Hi,

is it possible to get support for Ionic 4.

**Comment by danielabbatt** [comment]
You mean Ionic 3 / Angular 4?

**Comment by aBuder** [comment]
Yes, thats right

**Comment by rossmartin** [comment]
Sorry I've been busy lately.  The weather has gotten nice in the northern hemisphere and I'm focusing on a side project using react native (excuses excuses I know).  I might have time to look into it this weekend.

**Comment by cquezpro** [comment]
any update for this?

**Comment by cquezpro** [comment]
it doesn't work with "@angular/core": "4.0.0"

**Comment by sirius2013** [comment]
it doesn't work with "@angular/core": "4.0.0"

**Comment by datacomp** [comment]
Hi,
I am also using this library in ionic3 but having issue in scrolling to index. can you please fix and update this library?

**Comment by rossmartin** [comment]
resolved via https://github.com/rossmartin/ionic2-alpha-scroll/pull/17

New major version 2.0.0 is available with this PR.
