### ISSUE TITLE
Update for use with Ionic 2/Angular 2 Release Versions

### ISSUE THREAD

**Issue by kierer** [rossmartin/ionic2-alpha-scroll#2]

**Comment by rossmartin** [comment]
This component is currently setup to work with [Ionic 2 beta 11](https://github.com/driftyco/ionic/blob/master/CHANGELOG.md) and Angular 2 RC4.

Is there a new beta for Ionic?

**Comment by Nishchit14** [comment]
Ionic2-rc0 released.
Where **directory** concept removed and **NgModule** concept introduced.
Please upgrade it to use with latest Ionic2.0

**Comment by rossmartin** [comment]
@Nishchit14 at the time of my comment above RC0 had not been released yet.  I do plan on updating this to work with RC0 but sorry I've just been so damn busy lately.  Thanks.

**Comment by Nishchit14** [comment]
@rossmartin Thanks man, Take your time. Your work is so helpful to community.

**Comment by andrucz** [comment]
I've just forked and made a commit to run with Ionic 2 RC 2: https://github.com/andrucz/ionic2-alpha-scroll

I need help testing it.

**Comment by rossmartin** [comment]
I'll have time to test later.  A pull request is welcome too.

**Comment by andrucz** [comment]
Created a PR for you to review the changes I made so far. There is still some work to do.

**Comment by andrucz** [comment]
Today I created an application with RC2, based on https://github.com/rossmartin/ionic2-alpha-scroll-example and it seems to be working.

**Comment by rossmartin** [comment]
@andrucz I created a new Ionic 2 project and installed the component from your forked repo but I'm seeing some errors that prevent building.

In a brand new project I ran - 
```
npm install https://github.com/andrucz/ionic2-alpha-scroll --save
```

I try to do a build after installing and this is what I see - 

![image](https://cloud.githubusercontent.com/assets/2498502/20164240/95e9a4d4-a6c8-11e6-9899-c3137c8460e1.png)

Any ideas?  Do you not experience this issue?

Here is my setup - 
```
Cordova CLI: 6.2.0 
Ionic Framework Version: 2.0.0-rc.2
Ionic CLI Version: 2.1.7
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.42
ios-deploy version: 1.8.6 
ios-sim version: 5.0.6 
OS: OS X El Capitan
Node Version: v6.3.1
Xcode version: Xcode 8.1 Build version 8B62
```
``` TypeScript version: 2.0.8```

**Comment by andrucz** [comment]
I forgot to mention that I tested after copying the artifacts generated by executing "npm install" on ionic2-alpha-scroll folder to node_modules/ionic2-alpha-scroll/

Those artifacts are in .gitignore, so just "npm install"ing from Github won't work (is it a problem?). They are listed in "files" property of package.json, so they will be published to npm and "npm install ionic2-alpha-scroll" will work.

Also, I made a commit today updating tsconfig.json file to match the one generated by Ionic when creating a new application.

**Comment by rossmartin** [comment]
@andrucz It turns out I had old dependencies in my local copy of the ionic2-alpha-scroll repo that were causing problems.  Thank you for putting in the work to get this component updated to be compatible with RC0 and higher.

I've fetched your latest fork into a local branch and tested it out.  I'm going to merge your PR and make a few changes.  I plan to keep the class name for the component as `IonAlphaScroll` and not `Ionic2AlphaScroll` in your fork.

**Comment by andrucz** [comment]
I'm glad it worked, Probably I will use your component on my next project. Thanks.

**Comment by rossmartin** [comment]
@Nishchit14 As of version [1.0.5](https://github.com/rossmartin/ionic2-alpha-scroll/tree/1.0.5) the component is usable with Ionic RC0 -> RC2.  Closing this now.
